/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as utils from "./utils";
export { AttestationService__factory } from "./AttestationService__factory";
