# Sample workflow for building and deploying a Next.js site to GitHub Pages
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main", "feature/*", "fix/*"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && 'pages' || format('pages-{0}', github.ref) }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
      NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_API_KEY }}
      NEXT_PUBLIC_ONCHAINKIT_API_KEY: ${{ secrets.NEXT_PUBLIC_ONCHAINKIT_API_KEY }}
      NEXT_PUBLIC_POAP_API_KEY: ${{ secrets.NEXT_PUBLIC_POAP_API_KEY }}
      NEXT_PUBLIC_DEFAULT_CHAIN: ${{ secrets.NEXT_PUBLIC_DEFAULT_CHAIN }}
      NEXT_PUBLIC_BASE_MAINNET_RPC_URL: ${{ secrets.NEXT_PUBLIC_BASE_MAINNET_RPC_URL }}
      NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL: ${{ secrets.NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL }}
      NEXT_PUBLIC_IGNORE_BUILD_ERROR: "true"
      NODE_VERSION: "18.17.0"
      GITHUB_PAGES: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.17.0"
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: |
          mkdir -p out
          touch out/.nojekyll
          yarn build
          yarn postbuild
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
      NEXT_PUBLIC_ALCHEMY_API_KEY: ${{ secrets.NEXT_PUBLIC_ALCHEMY_API_KEY }}
      NEXT_PUBLIC_ONCHAINKIT_API_KEY: ${{ secrets.NEXT_PUBLIC_ONCHAINKIT_API_KEY }}
      NEXT_PUBLIC_POAP_API_KEY: ${{ secrets.NEXT_PUBLIC_POAP_API_KEY }}
      NEXT_PUBLIC_DEFAULT_CHAIN: ${{ secrets.NEXT_PUBLIC_DEFAULT_CHAIN }}
      NEXT_PUBLIC_BASE_MAINNET_RPC_URL: ${{ secrets.NEXT_PUBLIC_BASE_MAINNET_RPC_URL }}
      NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL: ${{ secrets.NEXT_PUBLIC_BASE_SEPOLIA_RPC_URL }}
      NEXT_PUBLIC_IGNORE_BUILD_ERROR: "true"
      NODE_VERSION: "18.17.0"
      GITHUB_PAGES: "true"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v3
        id: deployment
